### ISSUE TITLE
Zero-indexing where a list may be empty

### ISSUE THREAD

**Issue by mikejgray** [OpenJarbas/tutubo#1]
tutubo.models.featured_videos[0]["image"]

This failed for one of my YouTube searches, not sure which one, but should validate that the list isn't empty before parsing

**Comment by JarbasAl** [comment]
i believe this is now fixed in version 0.0.2a1 , please reopen if not

**Comment by mikejgray** [comment]
https://github.com/OpenJarbas/tutubo/blob/8042c640a123e5af6668651c5cdac8ee3b68b490/tutubo/models.py#L335

This is consistently causing an error still
